CREATE CONSTRAINT IF NOT EXISTS
FOR (p:Person) REQUIRE p.id IS UNIQUE;

CREATE CONSTRAINT IF NOT EXISTS
FOR (c:Country) REQUIRE c.name IS UNIQUE;

CREATE CONSTRAINT IF NOT EXISTS
FOR (s:Sanction) REQUIRE s.name IS UNIQUE;

CREATE CONSTRAINT IF NOT EXISTS
FOR (a:Alias) REQUIRE a.name IS UNIQUE;
