import ollama

# Country code to name mapping
COUNTRY_NAMES = {
    'ru': 'Russia',
    'sv': 'El Salvador',
    'ar': 'Argentina',
    'in': 'India',
    'pk': 'Pakistan',
    'gt': 'Guatemala',
    'bo': 'Bolivia',
    'us': 'United States',
    'az': 'Azerbaijan',
    'ge': 'Georgia',
    'cn': 'China',
    'mx': 'Mexico',
    'co': 'Colombia',
    've': 'Venezuela',
    'ir': 'Iran',
    'sy': 'Syria',
    'kp': 'North Korea',
    'iq': 'Iraq',
    'af': 'Afghanistan',
    'ly': 'Libya',
    'sd': 'Sudan',
    'ye': 'Yemen',
}


def expand_country_names(results):
    """
    Convert country codes to full names in results.
    """
    expanded = []
    for record in results:
        record_copy = record.copy()
        if 'country' in record_copy:
            code = record_copy['country'].lower()
            record_copy['country'] = COUNTRY_NAMES.get(code, code.upper())
        expanded.append(record_copy)
    return expanded


def format_results_for_llm(results, query_plan):
    """
    Format results into a string suitable for the LLM prompt.
    """
    intent = query_plan.get('intent', '')
    
    if intent == 'rank':
        # Format ranking results
        lines = []
        for i, record in enumerate(results[:10], 1):  # Top 10
            country = record.get('country', record.get('group', 'Unknown'))
            count = record.get('sanctioned_count', record.get('value', 0))
            lines.append(f"{i}. {country}: {count:,} individuals")
        return "\n".join(lines)
    
    elif intent == 'count':
        # Format count results
        count = results[0].get('count', 0)
        return f"Total count: {count:,}"
    
    elif intent == 'list':
        # Format list results
        items = [record.get('name', 'Unknown') for record in results[:20]]
        return "\n".join(f"- {item}" for item in items)
    
    elif intent == 'find':
        # Format find results
        lines = []
        for record in results[:10]:
            name = record.get('name', 'Unknown')
            country = record.get('country', '')
            if country:
                lines.append(f"- {name} (from {country})")
            else:
                lines.append(f"- {name}")
        return "\n".join(lines)
    
    else:
        # Generic formatting
        return "\n".join(str(record) for record in results[:10])


def generate_simple_response(question, results, query_plan):
    """
    Fallback simple response generator without LLM.
    """
    intent = query_plan.get('intent', '')
    
    if intent == 'rank' and 'country' in results[0]:
        top_countries = []
        for i, record in enumerate(results[:5], 1):
            country = record.get('country', 'Unknown')
            count = record.get('sanctioned_count', record.get('value', 0))
            top_countries.append(f"{country} ({count:,})")
        
        countries_str = ", ".join(top_countries[:3])
        if len(results) > 3:
            countries_str += f", and {len(results) - 3} others"
        
        return f"The countries with the most sanctioned individuals are {countries_str}."
    
    elif intent == 'count':
        count = results[0].get('count', 0)
        return f"There are {count:,} results matching your query."
    
    else:
        return f"I found {len(results)} results for your question."


def generate_natural_response(question, results, query_plan):
    """
    Convert structured query results into natural language using LLM.
    
    Args:
        question: The original user question
        results: List of result dictionaries from Neo4j
        query_plan: The plan generated by reason_over_question
    
    Returns:
        Natural language response string
    """
    # Format results into a readable string
    if not results:
        return "I couldn't find any results for your question."
    
    # Create a summary of the results
    results_summary = format_results_for_llm(results, query_plan)
    
    prompt = f"""
You are a helpful assistant answering questions about sanctioned individuals and organizations.

Original question: {question}

Query results:
{results_summary}

Generate a natural, conversational response that:
1. Directly answers the question in a complete sentence
2. Highlights the most important findings (top 3-5 items)
3. Uses proper formatting (numbers with commas)
4. Is concise but informative (2-3 sentences maximum)
5. Sounds human and friendly

Do not include phrases like "Based on the results" or "According to the data". Just answer directly.

Response:"""
    
    try:
        response = ollama.chat(
            model='phi3',
            messages=[
                {
                    'role': 'user',
                    'content': prompt
                }
            ]
        )
        
        return response['message']['content'].strip()
    
    except Exception as e:
        # Fallback to simple formatting if LLM fails
        print(f"Warning: LLM failed, using simple response. Error: {e}")
        return generate_simple_response(question, results, query_plan)